# Base de données
spring.datasource.url=jdbc:mysql://localhost:3306/bibliotheque_db
spring.datasource.username=biblio_user
spring.datasource.password=biblio2024
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Port du serveur
server.port=8080

# Nom de l'application
spring.application.name=bibliotheque

# Désactiver Spring Security par défaut
spring.security.user.name=admin
spring.security.user.password=admin123